/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_PRIMARY_ADDRESS_H
#define _MOCK_PRIMARY_ADDRESS_H

#include "../../lib/cmock/vendor/unity/src/unity.h"
#include "../../../src/headers/primary_address.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_primary_address_Init(void);
void mock_primary_address_Destroy(void);
void mock_primary_address_Verify(void);




#define input_primary_residence_ExpectAndReturn(root, cmock_retval) input_primary_residence_CMockExpectAndReturn(__LINE__, root, cmock_retval)
void input_primary_residence_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cJSON* root, int cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
