/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "../../lib/cmock/src/cmock.h"
#include "mock_primary_address.h"

static const char* CMockString_input_primary_residence = "input_primary_residence";
static const char* CMockString_root = "root";

typedef struct _CMOCK_input_primary_residence_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  cJSON* Expected_root;

} CMOCK_input_primary_residence_CALL_INSTANCE;

static struct mock_primary_addressInstance
{
  CMOCK_MEM_INDEX_TYPE input_primary_residence_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_primary_address_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.input_primary_residence_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_input_primary_residence);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_primary_address_Init(void)
{
  mock_primary_address_Destroy();
}

void mock_primary_address_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int input_primary_residence(cJSON* root)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_input_primary_residence_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_input_primary_residence);
  cmock_call_instance = (CMOCK_input_primary_residence_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.input_primary_residence_CallInstance);
  Mock.input_primary_residence_CallInstance = CMock_Guts_MemNext(Mock.input_primary_residence_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_input_primary_residence,CMockString_root);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_root), (void*)(root), sizeof(cJSON), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_input_primary_residence(CMOCK_input_primary_residence_CALL_INSTANCE* cmock_call_instance, cJSON* root)
{
  cmock_call_instance->Expected_root = root;
}

void input_primary_residence_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cJSON* root, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_input_primary_residence_CALL_INSTANCE));
  CMOCK_input_primary_residence_CALL_INSTANCE* cmock_call_instance = (CMOCK_input_primary_residence_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.input_primary_residence_CallInstance = CMock_Guts_MemChain(Mock.input_primary_residence_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_input_primary_residence(cmock_call_instance, root);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

