.TH "basic" 3 "Thu Dec 3 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBfirst_name\fP [32]"
.br
.ti -1c
.RI "char \fBlast_name\fP [32]"
.br
.ti -1c
.RI "char \fBemail\fP [64]"
.br
.ti -1c
.RI "char \fBsin\fP [10]"
.br
.ti -1c
.RI "char \fBdate_of_birth\fP [12]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file new_taxfile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
