.TH "cJSON_Hooks" 3 "Thu Dec 3 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cJSON_Hooks
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void *CJSON_CDECL * \fBmalloc_fn\fP (size_t sz)"
.br
.ti -1c
.RI "\fBvoid\fP (CJSON_CDECL *free_fn)(void *ptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 125 of file cJSON\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
