.TH "src/dependent_details.c" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dependent_details.c \- Contains the definition for getting users Dependent details\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'headers/dependent_details\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'headers/commons\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_RETRIES\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinput_dependent_details\fP (\fBcJSON\fP *root)"
.br
.RI "Gets Dependent details from the user\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the definition for getting users Dependent details\&. 


.PP
Definition in file \fBdependent_details\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int input_dependent_details (\fBcJSON\fP * root)"

.PP
Gets Dependent details from the user\&. @detail Asks user to fill in details of their dependents
.PP
\fBParameters\fP
.RS 4
\fIJSON\fP root element
.RE
.PP
\fBReturns\fP
.RS 4
0 in case of success or 1 in case of failure 
.RE
.PP

.PP
Definition at line 24 of file dependent_details\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
