.TH "dependent_details" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dependent_details
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBdependent_name\fP [1024]"
.br
.ti -1c
.RI "char \fBrelationship\fP [20]"
.br
.ti -1c
.RI "char \fBdisability\fP [5]"
.br
.ti -1c
.RI "char \fBclaim_child_care_benefits\fP [5]"
.br
.ti -1c
.RI "double \fBdependent_net_income\fP"
.br
.ti -1c
.RI "char \fBdependent_dob\fP [20]"
.br
.ti -1c
.RI "int \fBdependent_age\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file dependent_details\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
