.TH "src/display_guide.c" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/display_guide.c \- Contains the definition for displaying the User manual\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdisplay_file\fP (char *filename)"
.br
.RI "Display User manual\&. "
.ti -1c
.RI "int \fBdisplay_guide\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the definition for displaying the User manual\&. 


.PP
\fBAuthor\fP
.RS 4
Ragunath Anbarasu 
.RE
.PP

.PP
Definition in file \fBdisplay_guide\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int display_file (char * filename)"

.PP
Display User manual\&. @detail Ask user to select which User manual to view and display
.PP
\fBParameters\fP
.RS 4
\fIJSON\fP root element
.RE
.PP
\fBReturns\fP
.RS 4
0 in case of success or 1 in case of failure 
.RE
.PP

.PP
Definition at line 20 of file display_guide\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
