.TH "entry_status" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
entry_status
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBdate_of_entry\fP [12]"
.br
.ti -1c
.RI "char \fBcurrent_province\fP [32]"
.br
.ti -1c
.RI "char \fBis_resident_in_tax_filing_year\fP [5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file entry_status\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
