.TH "internal_hooks" 3 "Thu Dec 3 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal_hooks
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void *CJSON_CDECL * \fBallocate\fP (size_t size)"
.br
.ti -1c
.RI "\fBvoid\fP (CJSON_CDECL *deallocate)(void *pointer)"
.br
.ti -1c
.RI "void *CJSON_CDECL * \fBreallocate\fP (void *pointer, size_t size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 156 of file cJSON\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
