.TH "src/main.c" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- Contains the definition for executing the tax calcualte function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include '\&.\&./include/cJSON\&.h'\fP
.br
\fC#include 'headers/commons\&.h'\fP
.br
\fC#include 'headers/primary_address\&.h'\fP
.br
\fC#include 'headers/t4\&.h'\fP
.br
\fC#include 'headers/mailing_address\&.h'\fP
.br
\fC#include 'headers/new_taxfile\&.h'\fP
.br
\fC#include 'headers/calculate_tax\&.h'\fP
.br
\fC#include 'headers/entry_status\&.h'\fP
.br
\fC#include 'headers/maritial_status\&.h'\fP
.br
\fC#include 'headers/world_income\&.h'\fP
.br
\fC#include 'headers/t2202\&.h'\fP
.br
\fC#include 'headers/spouse_details\&.h'\fP
.br
\fC#include 'headers/dependent_details\&.h'\fP
.br
\fC#include 'headers/ot_benefits\&.h'\fP
.br
\fC#include 'headers/generate_pdf\&.h'\fP
.br
\fC#include 'headers/gst_hst\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "Gets details and calculate tax from the user\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the definition for executing the tax calcualte function\&. 


.PP
\fBAuthor\fP
.RS 4
Ragunath Anbrasu, Prathmesh Ranaut , Shreya Dhanani 
.RE
.PP

.PP
Definition in file \fBmain\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Gets details and calculate tax from the user\&. @detail Asks user to fill in the necessary details for calculation of tax and output a PDF file\&.
.PP
\fBParameters\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 38 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
