.TH "maritial_status" 3 "Thu Dec 3 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maritial_status
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBcurrent_maritial_status\fP [32]"
.br
.ti -1c
.RI "char \fBis_change_of_status\fP [5]"
.br
.ti -1c
.RI "char \fBdate_of_change\fP [12]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file maritial_status\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
