.TH "src/maritial_status.c" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/maritial_status.c \- Contains the definition for getting users marital status details\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'headers/maritial_status\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'headers/commons\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_RETRIES\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinput_maritial_status\fP (\fBcJSON\fP *root)"
.br
.RI "Gets Marital details from the user\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the definition for getting users marital status details\&. 


.PP
\fBAuthor\fP
.RS 4
Shreya Dhanani 
.RE
.PP

.PP
Definition in file \fBmaritial_status\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int input_maritial_status (\fBcJSON\fP * root)"

.PP
Gets Marital details from the user\&. @detail Asks user to fill in marital details so that it can be used in calculation of tax
.PP
\fBParameters\fP
.RS 4
\fIJSON\fP root element
.RE
.PP
\fBReturns\fP
.RS 4
0 in case of success or 1 in case of failure 
.RE
.PP

.PP
Definition at line 23 of file maritial_status\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
