.TH "ot_benefits" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ot_benefits
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBage\fP [5]"
.br
.ti -1c
.RI "double \fBincome\fP"
.br
.ti -1c
.RI "char \fBsocial_assistance\fP [5]"
.br
.ti -1c
.RI "double \fBsocial_assistance_receive\fP"
.br
.ti -1c
.RI "double \fBsocial_assistance_repay\fP"
.br
.ti -1c
.RI "char \fBspouse\fP [5]"
.br
.ti -1c
.RI "char \fBspouse_age\fP [5]"
.br
.ti -1c
.RI "double \fBspouse_income\fP"
.br
.ti -1c
.RI "char \fBspouse_social_assistance\fP [5]"
.br
.ti -1c
.RI "double \fBspouse_social_assistance_receive\fP"
.br
.ti -1c
.RI "double \fBspouse_social_assistance_repay\fP"
.br
.ti -1c
.RI "char \fBchildren\fP [5]"
.br
.ti -1c
.RI "char \fBchildren_dtc\fP [5]"
.br
.ti -1c
.RI "char \fBchildren_age\fP [5]"
.br
.ti -1c
.RI "char \fBhouse\fP [5]"
.br
.ti -1c
.RI "double \fBhouse_r_rent\fP"
.br
.ti -1c
.RI "char \fBhouse_r_long_term_care\fP [5]"
.br
.ti -1c
.RI "char \fBhouse_r_long_term_care_type\fP [10]"
.br
.ti -1c
.RI "double \fBhouse_o_tax\fP"
.br
.ti -1c
.RI "double \fBhouse_ro_rent\fP"
.br
.ti -1c
.RI "double \fBhouse_ro_tax\fP"
.br
.ti -1c
.RI "char \fBhouse_ro_long_term_care\fP [5]"
.br
.ti -1c
.RI "char \fBhouse_ro_long_term_care_type\fP [10]"
.br
.ti -1c
.RI "char \fBcollege_residence\fP [5]"
.br
.ti -1c
.RI "char \fBfirst_nations_reserve\fP [5]"
.br
.ti -1c
.RI "double \fBfirst_nations_reserve_energy_cost\fP"
.br
.ti -1c
.RI "char \fBnorthern_ontario\fP [5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file ot_benefits\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
