.TH "parse_buffer" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parse_buffer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned char * \fBcontent\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.ti -1c
.RI "size_t \fBoffset\fP"
.br
.ti -1c
.RI "size_t \fBdepth\fP"
.br
.ti -1c
.RI "\fBinternal_hooks\fP \fBhooks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 287 of file cJSON\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
