.TH "pdf_doc" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdf_doc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBerrstr\fP [128]"
.br
.ti -1c
.RI "int \fBerrval\fP"
.br
.ti -1c
.RI "struct \fBflexarray\fP \fBobjects\fP"
.br
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.ti -1c
.RI "struct \fBpdf_object\fP * \fBcurrent_font\fP"
.br
.ti -1c
.RI "struct \fBpdf_object\fP * \fBlast_objects\fP [OBJ_count]"
.br
.ti -1c
.RI "struct \fBpdf_object\fP * \fBfirst_objects\fP [OBJ_count]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 210 of file pdfgen\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
