.TH "primary_address" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
primary_address
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBstreet_number\fP [32]"
.br
.ti -1c
.RI "char \fBstreet_name\fP [32]"
.br
.ti -1c
.RI "char \fBcity\fP [32]"
.br
.ti -1c
.RI "char \fBprovince\fP [32]"
.br
.ti -1c
.RI "char \fBpostal_code\fP [8]"
.br
.ti -1c
.RI "char \fBcontact_number\fP [20]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file primary_address\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
