.TH "printbuffer" 3 "Thu Dec 3 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
printbuffer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.ti -1c
.RI "size_t \fBoffset\fP"
.br
.ti -1c
.RI "size_t \fBdepth\fP"
.br
.ti -1c
.RI "cJSON_bool \fBnoalloc\fP"
.br
.ti -1c
.RI "cJSON_bool \fBformat\fP"
.br
.ti -1c
.RI "\fBinternal_hooks\fP \fBhooks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 427 of file cJSON\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
