.TH "spouse_details" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spouse_details
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBspouse_name\fP [1024]"
.br
.ti -1c
.RI "char \fBspouse_dob\fP [20]"
.br
.ti -1c
.RI "double \fBspouse_net_income\fP"
.br
.ti -1c
.RI "char \fBspouse_sin\fP [20]"
.br
.ti -1c
.RI "char \fBspouse_care_benefits\fP [5]"
.br
.ti -1c
.RI "int \fBspouse_age\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file spouse_details\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
