.TH "t2202" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t2202
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBinstitute_name\fP [1024]"
.br
.ti -1c
.RI "char \fBschool_type\fP [32]"
.br
.ti -1c
.RI "char \fBstudent_number\fP [32]"
.br
.ti -1c
.RI "char \fBcourse\fP [32]"
.br
.ti -1c
.RI "char \fBsession\fP [32]"
.br
.ti -1c
.RI "double \fBamount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file t2202\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
