.TH "t4" 3 "Sat Dec 19 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t4
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBemployer_name\fP [1024]"
.br
.ti -1c
.RI "char \fBprovince\fP [3]"
.br
.ti -1c
.RI "double \fBemployment_income\fP"
.br
.ti -1c
.RI "double \fBemployees_cpp_contribution\fP"
.br
.ti -1c
.RI "double \fBemployees_qpp_contribution\fP"
.br
.ti -1c
.RI "double \fBemployees_ei_premiums\fP"
.br
.ti -1c
.RI "double \fBrpp_contributions\fP"
.br
.ti -1c
.RI "double \fBincome_tax_deducted\fP"
.br
.ti -1c
.RI "double \fBei_insurable_earnings\fP"
.br
.ti -1c
.RI "double \fBcpp_qpp_pensionable_earnings\fP"
.br
.ti -1c
.RI "double \fBunion_dues\fP"
.br
.ti -1c
.RI "double \fBcharitable_donations\fP"
.br
.ti -1c
.RI "double \fBrpp_dssp_registation_number\fP"
.br
.ti -1c
.RI "double \fBpension_adjustment\fP"
.br
.ti -1c
.RI "double \fBemployees_ppip_premiums\fP"
.br
.ti -1c
.RI "double \fBppip_insurable_earnings\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file t4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
