.TH "tax" 3 "Thu Dec 3 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tax
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBfederal_tax\fP"
.br
.ti -1c
.RI "double \fBincome_tax\fP"
.br
.ti -1c
.RI "double \fBprovencial_tax\fP"
.br
.ti -1c
.RI "double \fBrefund\fP"
.br
.ti -1c
.RI "double \fBpayable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file calculate_tax\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
