.TH "UNITY_STORAGE_T" 3 "Thu Dec 3 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNITY_STORAGE_T
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBTestFile\fP"
.br
.ti -1c
.RI "const char * \fBCurrentTestName\fP"
.br
.ti -1c
.RI "const char * \fBCurrentDetail1\fP"
.br
.ti -1c
.RI "const char * \fBCurrentDetail2\fP"
.br
.ti -1c
.RI "UNITY_LINE_TYPE \fBCurrentTestLineNumber\fP"
.br
.ti -1c
.RI "UNITY_COUNTER_TYPE \fBNumberOfTests\fP"
.br
.ti -1c
.RI "UNITY_COUNTER_TYPE \fBTestFailures\fP"
.br
.ti -1c
.RI "UNITY_COUNTER_TYPE \fBTestIgnores\fP"
.br
.ti -1c
.RI "UNITY_COUNTER_TYPE \fBCurrentTestFailed\fP"
.br
.ti -1c
.RI "UNITY_COUNTER_TYPE \fBCurrentTestIgnored\fP"
.br
.ti -1c
.RI "jmp_buf \fBAbortFrame\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 456 of file unity_internals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
