.TH "world_income" 3 "Thu Dec 3 2020" "Version 1.0" "Tax Filing Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
world_income
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBcanadian_source_of_income\fP"
.br
.ti -1c
.RI "double \fBforeign_source_of_income\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file world_income\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tax Filing Software from the source code\&.
